import Head from 'next/head'
import Hero  from './components/Hero'
import Image from 'next/image'
//import { Inter } from '@next/font/google'


//const inter = Inter({ subsets: ['latin'] })
 function Home() {
  return (
    <>
      <Head>
        <title>CS3-Official Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading = 'Bringing Your Tech-Ideas To Reality' message = 'We create value for our customer leaveraging on technology' />
      

      
    </>
  )
}



export default Home
